#!/usr/bin/env bash
# Download source PDFs into corpus/ and write corpus/MANIFEST.txt.
set -uo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CORPUS_DIR="$REPO_ROOT/corpus"
MANIFEST="$CORPUS_DIR/MANIFEST.txt"

mkdir -p "$CORPUS_DIR"
log()   { printf '[corpus] %s\n' "$*"; }
warn()  { printf '[corpus][warn] %s\n' "$*" >&2; }
err()   { printf '[corpus][err]  %s\n' "$*" >&2; }

pdf_pages() {
  local f=$1
  if command -v pdfinfo >/dev/null 2>&1; then
    pdfinfo "$f" 2>/dev/null | awk '/^Pages:/ {print $2; exit}'
  elif command -v mdls >/dev/null 2>&1; then
    local n
    n=$(mdls -name kMDItemNumberOfPages -raw "$f" 2>/dev/null)
    [[ -n "$n" && "$n" != "(null)" ]] && echo "$n" || echo "?"
  else
    echo "?"
  fi
}

# Some publisher PDF URLs return HTML with HTTP 200; verify the magic header.
is_pdf() {
  local f=$1
  [[ -s "$f" ]] || return 1
  local magic
  magic=$(head -c 5 "$f" 2>/dev/null)
  [[ "$magic" == "%PDF-" ]]
}

DIRECT_FAILED=0
direct_download() {
  local slug=$1 url=$2 title=$3 fb_landing=${4:-$url} fb_hint=${5:-"download manually from the publisher's landing page"}
  local out="$CORPUS_DIR/$slug.pdf"
  local status

  if is_pdf "$out"; then
    log "skip:  $slug.pdf (already present, $(wc -c < "$out" | tr -d ' ') bytes)"
    status="skipped"
  else
    [[ -e "$out" ]] && rm -f "$out"
    log "fetch: $slug → $url"
    if curl -fsSL --retry 2 --connect-timeout 15 --max-time 180 -o "$out.partial" "$url"; then
      if is_pdf "$out.partial"; then
        mv "$out.partial" "$out"
        status="downloaded"
      else
        warn "  $url returned non-PDF content (likely SPA/HTML wrapper); falling back to manual instruction"
        rm -f "$out.partial"
        manual_instruction "$slug" "$fb_landing" "$title" "$fb_hint"
        return 0
      fi
    else
      rm -f "$out.partial"
      err "  failed: $url"
      DIRECT_FAILED=$((DIRECT_FAILED + 1))
      manual_instruction "$slug" "$fb_landing" "$title" "$fb_hint"
      return 0
    fi
  fi

  local pages="?"
  is_pdf "$out" && pages=$(pdf_pages "$out")
  manifest_row "$slug.pdf" "$title" "$url" "$pages" "$status"
}

manual_instruction() {
  local slug=$1 landing=$2 title=$3 hint=$4
  local out="$CORPUS_DIR/$slug.pdf"
  local status

  if [[ -s "$out" ]]; then
    log "skip:  $slug.pdf (manual file already in place)"
    status="manual-present"
  else
    cat <<EOF
[corpus] manual download required: $slug.pdf
        title: $title
        page : $landing
        hint : $hint
        save as: corpus/$slug.pdf
EOF
    status="manual-required"
  fi

  local pages="?"
  [[ -s "$out" ]] && pages=$(pdf_pages "$out")
  manifest_row "$slug.pdf" "$title" "$landing" "$pages" "$status"
}
now_iso() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }

cat > "$MANIFEST" <<EOF
# corpus/MANIFEST.txt — generated by scripts/download_corpus.sh
# Corpus bundle version: v1.5.3   |   the source-corpus bundle source corpus (10-15 PDFs)
# Run timestamp: $(now_iso)
#
# Columns: <file>\t<title>\t<source_url>\t<pages>\t<status>
EOF

manifest_row() {
  printf '%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "$5" >> "$MANIFEST"
}

direct_download \
  "who_anc_2016" \
  "https://iris.who.int/bitstream/handle/10665/250796/9789241549912-eng.pdf" \
  "WHO recommendations on antenatal care for a positive pregnancy experience (2016)" \
  "https://www.who.int/publications/i/item/9789241549912" \
  "Open the WHO publications page; click 'Download' on the English PDF link"

direct_download \
  "who_anc_2024_update" \
  "https://iris.who.int/bitstream/handle/10665/376236/9789240088467-eng.pdf" \
  "WHO antenatal care recommendations — 2024 update (positive pregnancy experience, addendum)" \
  "https://www.who.int/publications/i/item/9789240088467" \
  "Open the WHO publications page; click 'Download' on the English PDF link"

direct_download \
  "who_lmm_2024" \
  "https://iris.who.int/bitstream/handle/10665/376803/9789240096059-eng.pdf" \
  "WHO Leadership and Management for Health (LMM) — 2024 governance reference" \
  "https://www.who.int/publications/i/item/9789240096059" \
  "Open the WHO publications page; click 'Download' on the English PDF link"
# Government pages require manual downloads because they gate PDFs behind UI.
manual_instruction \
  "mohfw_jsy_operational_guidelines" \
  "https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309" \
  "MoHFW Janani Suraksha Yojana — Operational Guidelines (the source-corpus bundle, source anchor P02)" \
  "Open the landing URL in a browser, click 'Operational Guidelines (English)' under Janani Suraksha Yojana"

manual_instruction \
  "mohfw_pmsma_operational_manual" \
  "https://pmsma.mohfw.gov.in/about-scheme/operational-guidelines/" \
  "MoHFW Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA) — Operational Guidelines (the source-corpus bundle, the shared MNH system prompt system_prompt)" \
  "Open the PMSMA portal, navigate to 'About scheme → Operational guidelines' and click the latest English PDF"

manual_instruction \
  "icmr_pregnancy_nutrition" \
  "https://main.icmr.nic.in/content/guidelines" \
  "ICMR pregnancy nutrition guidelines (the source-corpus bundle; ICMR Dietary Guidelines for Indians is the canonical reference)" \
  "Search 'pregnancy' / 'antenatal' on the ICMR guidelines page and download the most recent PDF"

manual_instruction \
  "asha_module_6_maternal_health" \
  "https://nhsrcindia.org/practice-areas/community-processes/training-resources" \
  "ASHA Module 6 — Skills that Save Lives: Maternal Health (the source-corpus bundle; cited in source anchor P05)" \
  "Open NHSRC training-resources page; locate 'Module 6 — Maternal Health' under ASHA training modules"

manual_instruction \
  "asha_module_7_child_health" \
  "https://nhsrcindia.org/practice-areas/community-processes/training-resources" \
  "ASHA Module 7 — Skills that Save Lives: Child Health (companion to Module 6, the source-corpus bundle)" \
  "Same NHSRC page as Module 6; download 'Module 7' immediately below"
log "manifest written: $MANIFEST"
log "PDFs in corpus/: $(ls -1 "$CORPUS_DIR"/*.pdf 2>/dev/null | wc -l | tr -d ' ')"

if [[ "$DIRECT_FAILED" -gt 0 ]]; then
  err "$DIRECT_FAILED direct download(s) failed — re-run after fixing network / URL drift"
  exit 1
fi

log "done."
